### ISSUE TITLE
install_requires Cuma Satu Library?

### ISSUE THREAD

**Issue by mzaini30** [michael-act/Senginta#3]
https://github.com/michael-act/Senginta/blob/90641b16bdcb83a23ab6b5a2d5c2424de756e336/setup.py#L24

Sedangkan, di `requitements.txt`, ada tiga library yang perlu diinstall.

https://github.com/michael-act/Senginta/blob/90641b16bdcb83a23ab6b5a2d5c2424de756e336/requirements.txt#L1-L3

Kalau mau otomatis, mungkin bisa pakai ini:

https://github.com/mzaini30/warna/blob/1ed1487d993ede00f851b8e11a369b9233939aa7/setup.py#L8-L14

**Comment by michael-act** [comment]
Terimakasih sudah membantu 😄. Repository ini sudah di update kembali, untuk project di pypi juga akan secepatnya di update.
